import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Star } from "lucide-react";
import { useLanguage } from "../hooks/useLanguage";
const ProductCard = ({ item }) => {
    const { language } = useLanguage();
    const name = language === "ar" ? item.nameAr : item.nameEn;
    return (_jsx(Link, { to: `/product/${item.id}`, children: _jsxs("div", { className: "bg-white dark:bg-bala-dark-surface rounded-bala overflow-hidden shadow-bala-light dark:shadow-bala-dark hover:shadow-bala-hover dark:hover:shadow-bala-dark transition-all duration-300 hover:-translate-y-1 group", children: [_jsxs("div", { className: "relative h-40 sm:h-56 overflow-hidden bg-bala-cream dark:bg-bala-dark-bg", children: [_jsx("img", { src: item.image, alt: name, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" }), item.popular && (_jsxs("div", { className: "absolute top-3 left-3 bg-bala-gold text-bala-forest px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1", children: [_jsx(Star, { size: 12 }), " ", language === 'ar' ? 'الأفضل' : 'Popular'] })), item.new && (_jsx("div", { className: "absolute top-3 right-3 bg-bala-forest dark:bg-bala-dark-green text-white px-3 py-1 rounded-full text-xs font-bold", children: language === 'ar' ? 'جديد' : 'New' }))] }), _jsxs("div", { className: "p-4 sm:p-6", children: [_jsx("h3", { className: "font-display text-xl sm:text-2xl font-extrabold text-bala-gold mb-3 line-clamp-2 text-center", children: name }), _jsxs("div", { className: "flex items-center justify-between gap-3", children: [_jsxs("div", { className: "text-xl sm:text-2xl font-display font-bold text-bala-forest dark:text-bala-cream", children: [item.price, " ", language === "ar" ? "ج" : "SAR"] }), _jsx("span", { className: "px-4 py-2 rounded-bala bg-bala-gold text-bala-forest font-extrabold text-sm sm:text-base hover:opacity-90 transition", children: language === "ar" ? "عرض" : "View" })] })] })] }) }));
};
export default ProductCard;
