import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import { ThemeProvider } from "./context/ThemeContext";
import { LanguageProvider } from "./context/LanguageContext";
import { CartProvider } from "./context/CartContext";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollToTop from "./components/ScrollToTop";
import Home from "./pages/Home";
import Menu from "./pages/Menu";
import MenuCategory from "./pages/MenuCategory";
import ProductDetails from "./pages/ProductDetails";
import Cart from "./pages/Cart";
import Checkout from "./pages/Checkout";
import Login from "./pages/Login";
import Register from "./pages/Register";
import Profile from "./pages/Profile";
import NotFound from "./pages/NotFound";
import { Offers } from "./pages/Offers";
import OfferDetails from "./pages/OfferDetails";
import GiftPage from "./pages/gift/GiftPage";
import GiftCheckout from "./pages/gift/GiftCheckout";
import GiftSuccess from "./pages/gift/GiftSuccess";
import GiftRedeem from "./pages/gift/GiftRedeem";
import GiftCreatePage from "./pages/gift/GiftCreatePage";
import GiftRedeemed from "./pages/gift/GiftRedeemed";
import RewardsPage from "./pages/rewards/RewardsPage";
const App = () => {
    return (_jsx(ThemeProvider, { children: _jsx(LanguageProvider, { children: _jsx(CartProvider, { children: _jsx(Router, { children: _jsxs("div", { className: "min-h-screen bg-[#efefef] *:dark:bg-bala-dark-bg flex flex-col", children: [_jsx(ScrollToTop, {}), _jsx(Navbar, {}), _jsx("main", { className: "flex-1", children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(Home, {}) }), _jsx(Route, { path: "/menu", element: _jsx(Menu, {}) }), _jsx(Route, { path: "/menu/:categoryId", element: _jsx(MenuCategory, {}) }), _jsx(Route, { path: "/product/:id", element: _jsx(ProductDetails, {}) }), _jsx(Route, { path: "/cart", element: _jsx(Cart, {}) }), _jsx(Route, { path: "/checkout", element: _jsx(Checkout, {}) }), _jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/register", element: _jsx(Register, {}) }), _jsx(Route, { path: "/profile", element: _jsx(Profile, {}) }), _jsx(Route, { path: "/offers", element: _jsx(Offers, {}) }), _jsx(Route, { path: "/offers/:offerId", element: _jsx(OfferDetails, {}) }), _jsx(Route, { path: "/gifts", element: _jsx(GiftPage, {}) }), _jsx(Route, { path: "/gift/create/:designId", element: _jsx(GiftCreatePage, {}) }), _jsx(Route, { path: "/gift/redeemed", element: _jsx(GiftRedeemed, {}) }), _jsx(Route, { path: "/gift/checkout", element: _jsx(GiftCheckout, {}) }), _jsx(Route, { path: "/gift/success", element: _jsx(GiftSuccess, {}) }), _jsx(Route, { path: "/gift/redeem", element: _jsx(GiftRedeem, {}) }), _jsx(Route, { path: "/rewards", element: _jsx(RewardsPage, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }) }), _jsx(Footer, {})] }) }) }) }) }));
};
export default App;
